[package]
name = "bolt11-forge"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = "0.32.6"
bitcoin_hashes = "0.16.0"
clap = { version = "4.5.42", features = ["derive"] }
hex = "0.4.3"
regex = "1.11.1"
secp256k1 = { version = "0.31.1", features = ["recovery"] }
